# Generated by Django 4.0.4 on 2022-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, max_length=300, upload_to='Desktop'),
        ),
    ]
